### ISSUE TITLE
"show-relation" doesn't seem to work on subordinate relations

### ISSUE THREAD

**Issue by Vultaire** [PietroPasotti/jhack#60]
I did a quick test of jhack locally on LXD, using an ubuntu unit and an nrpe subordinate.

My invocation of jhack was: ```jhack show-relation ubuntu:juju-info nrpe:general-info```

This gives the following traceback:

```
Traceback (most recent call last):
  File "/snap/jhack/120/bin/jhack", line 8, in <module>
    sys.exit(main())
  File "/snap/jhack/120/lib/python3.8/site-packages/jhack/main.py", line 134, in main
    app()
  File "/snap/jhack/120/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/snap/jhack/120/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/snap/jhack/120/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/snap/jhack/120/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/jhack/120/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/jhack/120/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/snap/jhack/120/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/snap/jhack/120/lib/python3.8/site-packages/jhack/utils/show_relation.py", line 572, in sync_show_relation
    return _sync_show_relation(
  File "/snap/jhack/120/lib/python3.8/site-packages/jhack/utils/show_relation.py", line 609, in _sync_show_relation
    table = asyncio.run(
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/snap/jhack/120/lib/python3.8/site-packages/jhack/utils/show_relation.py", line 459, in render_relation
    data = get_relation_data(
  File "/snap/jhack/120/lib/python3.8/site-packages/jhack/utils/show_relation.py", line 325, in get_relation_data
    provider_data = get_content(
  File "/snap/jhack/120/lib/python3.8/site-packages/jhack/utils/show_relation.py", line 238, in get_content
    other_unit_name = next(iter(status["applications"][other_app_name]["units"]))
KeyError: 'units'
```

I suspect the above issue is happening because juju status output for subordinate applications doesn't include a "units" dictionary; you'd have to go into the principal unit to find those subordinate units.

Reproduction steps:
* Use a Juju 2.9-series controller.  (Tested with Juju 2.9.38.)
* On a new model:
  * ```juju deploy ubuntu```
  * ```juju deploy nrpe```
  * ```juju add-relation ubuntu nrpe```
  * After deployed and settled, run ```jhack show-relation ubuntu:juju-info nrpe:general-info```.

**Comment by PietroPasotti** [comment]
Ummm, I was convinced I'd fixed this one. Will repro tomorrow. Thanks!

**Comment by Vultaire** [comment]
Actually, I missed an important detail; maybe this is resolved in later version?

Was running latest/stable, i.e. version 0.3.2.

**Comment by PietroPasotti** [comment]
yeah if you have time to check from edge that'd be great
